### ISSUE TITLE
Who is yashinko?

### ISSUE THREAD

**Issue by SteveBronder** [lorentzca/qmk_firmware-iris#9]
Sorry if this is a weird question, but we have a github account who I thought was a bot that merges commits from our develop branch to branches that haven't updated to develop yet (see [here](https://github.com/stan-dev/math/issues/2077) for more info). It's actually quite nice, but looking @yashikno up it looks like they have actual commits in your repo so I'm not sure if it's a bot or not

https://github.com/lorentzca/qmk_firmware-iris/commits?author=yashikno

Do you know who yashinko is?

**Comment by lorentzca** [comment]
Sorry for the late reply.
This repository is forked, but I'm not a committer for qmk_firmware, so I don't know the details of yashinko.
